# Generated by Django 6.0 on 2026-02-26 02:12

import django.db.models.deletion
import practicas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Objetivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción ampliada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_practica', to='users.program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Objetivo de Práctica',
                'verbose_name_plural': 'Objetivos de Práctica',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SitioPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del sitio')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitios_practica', to='users.program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Sitio de Práctica',
                'verbose_name_plural': 'Sitios de Práctica',
                'ordering': ['name'],
                'unique_together': {('name', 'program')},
            },
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la práctica')),
                ('year', models.IntegerField(default=2026, verbose_name='Año')),
                ('period', models.IntegerField(choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')], default=1, verbose_name='Semestre')),
                ('code', models.CharField(default=practicas.models.generate_practica_code, max_length=8, unique=True, verbose_name='Código QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_coordinadas', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador')),
                ('objetivos', models.ManyToManyField(blank=True, related_name='practicas', to='practicas.objetivopractica', verbose_name='Objetivos')),
                ('profesor_practica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor de Práctica')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='users.program', verbose_name='Programa')),
                ('students', models.ManyToManyField(blank=True, related_name='practicas_inscritas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes inscritos')),
                ('sitios', models.ManyToManyField(blank=True, related_name='practicas', to='practicas.sitiopractica', verbose_name='Sitios de práctica')),
            ],
            options={
                'verbose_name': 'Práctica',
                'verbose_name_plural': 'Prácticas',
                'ordering': ['-year', '-period', 'name'],
            },
        ),
    ]
