# Generated by Django 6.0 on 2026-02-26 02:38

import django.db.models.deletion
import practicas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitiopractica',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='sitiopractica',
            name='phone_fixed',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono fijo'),
        ),
        migrations.AddField(
            model_name='sitiopractica',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='practica',
            name='code',
            field=models.CharField(default=practicas.models.generate_practica_code, max_length=8, unique=True, verbose_name='Código de inscripción'),
        ),
        migrations.CreateModel(
            name='SeguimientoPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de visita')),
                ('topic', models.CharField(blank=True, max_length=300, verbose_name='Tema / actividad')),
                ('novedades', models.TextField(blank=True, verbose_name='Novedades')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='practicas.practica', verbose_name='Práctica')),
                ('sitio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practicas.sitiopractica', verbose_name='Sitio visitado')),
            ],
            options={
                'verbose_name': 'Seguimiento de Práctica',
                'verbose_name_plural': 'Seguimientos de Práctica',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('LATE', 'Tardanza'), ('EXCUSED', 'Excusado')], default='PRESENT', max_length=10)),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='practicas.seguimientopractica', verbose_name='Seguimiento')),
            ],
            options={
                'verbose_name': 'Asistencia Práctica',
                'verbose_name_plural': 'Asistencias Práctica',
                'unique_together': {('seguimiento', 'student')},
            },
        ),
    ]
