# Generated by Django 6.0 on 2026-02-26 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0002_sitiopractica_contact_name_sitiopractica_phone_fixed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciapractica',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comentario del coordinador'),
        ),
        migrations.CreateModel(
            name='ReflexionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividades', models.TextField(verbose_name='Actividades realizadas')),
                ('reflexion_pedagogica', models.TextField(blank=True, verbose_name='Reflexión pedagógica')),
                ('aprendizajes', models.TextField(blank=True, verbose_name='Aprendizajes y mejoras')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflexiones', to='practicas.seguimientopractica', verbose_name='Sesión de práctica')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflexiones_practica', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Reflexión de Estudiante',
                'verbose_name_plural': 'Reflexiones de Estudiantes',
                'ordering': ['-seguimiento__date'],
                'unique_together': {('seguimiento', 'student')},
            },
        ),
    ]
