# Generated by Django 5.2.17 on 2026-09-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminute',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
