# Generated by Django 6.0 on 2026-02-25 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='Lista de todos los roles del usuario', verbose_name='Roles activos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINATOR', 'Coordinador'), ('TEACHER', 'Docente'), ('STUDENT', 'Estudiante')], default='STUDENT', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.faculty', verbose_name='Facultad'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='users.faculty', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.program', verbose_name='Programa'),
        ),
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_type', models.CharField(choices=[('PRACTICAS', 'Prácticas'), ('PROGRAMA', 'Programa'), ('INVESTIGACION', 'Investigación'), ('EXTENSION', 'Extensión')], max_length=20, verbose_name='Tipo de coordinación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='users.program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Perfil de Coordinador',
                'verbose_name_plural': 'Perfiles de Coordinador',
                'unique_together': {('user', 'coordinator_type', 'program')},
            },
        ),
    ]
