# Generated by Django 6.0 on 2026-02-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_faculty_user_roles_alter_user_role_user_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINATOR', 'Coordinador'), ('TEACHER', 'Docente'), ('STUDENT', 'Estudiante'), ('PRACTICE_TEACHER', 'Profesor de Práctica')], default='STUDENT', max_length=20),
        ),
    ]
