# Generated by Django 5.2.17 on 2026-08-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
