# Generated by Django 6.0 on 2026-02-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
