# Generated by Django 6.0 on 2026-02-05 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_course_end_date_remove_course_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='group',
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
