# Generated by Django 6.0 on 2026-02-05 03:52

import academic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_course_group_course_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=academic.models.generate_course_code, max_length=8, unique=True),
        ),
    ]
