# Generated by Django 6.0 on 2026-02-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='excuse_file',
            field=models.FileField(blank=True, null=True, upload_to='excuses/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='excuse_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='excuse_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='excuse_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='excuse_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Presente'), ('LATE', 'Retardo'), ('ABSENT', 'Falta'), ('EXCUSED', 'Excusa')], max_length=10),
        ),
    ]
