# Generated by Django 6.0 on 2026-02-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_attendance_excuse_file_attendance_excuse_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
