# Generated by Django 6.0 on 2026-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_course_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(choices=[('blue', 'Azul'), ('violet', 'Violeta'), ('emerald', 'Esmeralda'), ('amber', 'Ámbar'), ('rose', 'Rosa'), ('cyan', 'Cian')], default='blue', max_length=10),
        ),
    ]
