# Generated by Django 5.2.17 on 2026-08-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_archive_existing_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='self_checkin_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='session',
            name='self_checkin_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='self_checkin_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
