# Generated by Django 5.2.17 on 2026-08-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_session_self_checkin_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='self_checkin_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
