# Generated by Codex on 2026-08-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_session_self_checkin_opened_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/')),
                ('group_size', models.PositiveSmallIntegerField(default=4)),
                ('inventory_name', models.CharField(blank=True, max_length=120)),
                ('inventory_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='academic.course')),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='MissionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('resource_type', models.CharField(choices=[('READING', 'Lectura'), ('YOUTUBE', 'YouTube'), ('LINK', 'Enlace'), ('FILE', 'Archivo')], max_length=10)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='mission_resources/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academic.mission')),
            ],
            options={'ordering': ('order', 'id')},
        ),
    ]
