# Generated by Django 5.2.17 on 2026-08-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_mission_missionresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Imagen de portada estilo Fortnite/Gamer', null=True, upload_to='missions/hero/'),
        ),
        migrations.AddField(
            model_name='mission',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Subtítulo épico para la cabecera de la Campaña', max_length=200),
        ),
        migrations.AddField(
            model_name='mission',
            name='lore_text',
            field=models.TextField(blank=True, help_text='Historia / Lore de la Campaña'),
        ),
    ]
